version: '3.5'
    
# Useful commands 
# https://github.ibm.com/GBS-Design/onboarding-dev/blob/master/docs/docker-compose.md

services: 
  
    db:
        container_name: demo_db
        hostname: db
        image: redis
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - "6379:6379"
        volumes:
          - ./demo-db:/var/lib/postgresql/data

    ui:
        container_name: demo_ui_foh
        build: ./demo-ui-foh
        hostname: ui-foh
         
        links:
          - api

        volumes:
          - ./demo-ui-foh:/demo_ui_foh  
          - /demo_ui_foh/node_modules
        ports:
          - "80:80"

    api:
        container_name: demo_api
        build: ./demo-api
        hostname: api
        depends_on:
          - db
         
        volumes:
          - ./demo-api:/demo_api
          - /demo_api/node_modules
        links: 
          - db 
        ports:
          - "81:81"