version: '3.5'

services: 
  
    db-ui: 
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        - REDIS_HOSTS=local:db:6379
      ports:
        - "8081:8081"
      links:
        - db
        
    db:
        container_name: db
        hostname: db
        image: redis
        ports:
          - "6379:6379"
        volumes:
          - ./db:/opt/redis

    ui:
        container_name: ui
        build: ./ui
        hostname: ui
        depends_on:
          - api
         
        links:
          - api

        volumes:
          - ./ui:/ui  
          - /ui/node_modules
        ports:
          - "80:80"

    api:
        container_name: api
        build: ./api
        hostname: api
        depends_on:
          - db
         
        volumes:
          - ./api:/api
          - /api/node_modules
        links: 
          - db 
        ports:
          - "81:81"

    nginx:
        image: nginx:latest
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - socket_1
          - socket_2
        ports:
          - "82:82"

    socket_1:
        build: ./socket
        hostname: socket_1
        depends_on:
          - api
          - db
         
        volumes:
          - ./socket:/socket
          - /socket/node_modules
        links: 
          - api 
          - db
        expose:
          - "83"

    socket_2:
        build: ./socket
        hostname: socket_2
        depends_on:
          - api
          - db
         
        volumes:
          - ./socket:/socket
          - /socket/node_modules
        links: 
          - api 
          - db
        expose:
          - "83"