version: '3.5'

services: 
  
    db-ui: 
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        - REDIS_HOSTS=local:db:6379
      ports:
        - "8081:8081"
      links:
        - db
        
    db:
        container_name: db
        hostname: db
        image: redis
        ports:
          - "6379:6379"
        volumes:
          - ./db:/opt/redis

    ui:
        container_name: ui
        build: ./ui
        hostname: ui
         
        # links:
        #   - api

        volumes:
          - ./ui:/ui  
          - /ui/node_modules
        ports:
          - "80:80"

    api:
        container_name: api
        build: ./api
        hostname: api
        depends_on:
          - db
         
        volumes:
          - ./api:/api
          - /api/node_modules
        links: 
          - db 
        ports:
          - "81:81"

    socket:
        container_name: socket
        build: ./socket
        hostname: socket
        depends_on:
          - api
         
        volumes:
          - ./socket:/socket
          - /api/node_modules
        links: 
          - api 
        ports:
          - "82:82"