version: '3.5'
    
# Useful commands 
# https://github.ibm.com/GBS-Design/onboarding-dev/blob/master/docs/docker-compose.md

services: 
  
    pptx: 
        container_name: orchard_pptx  
        build: ./orchard-pptx
        hostname: pptx
        ports:
          - "7002:3000"

    db:
        container_name: orchard_db
        hostname: db
        image: postgres 
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - "5436:5432"
        volumes:
          - ./orchard-db:/var/lib/postgresql/data

    adminer:
        container_name: orchard_adminer
        image: adminer 
        ports:
          - "7036:8080"
        links: 
          - db

    ui:
        container_name: orchard_ui
        build: ./orchard-ui
        hostname: ui
        restart: on-failure
         
        links:
          - ui-foh
          - ui-boh

        volumes:
          - ./orchard-ui:/orchard_ui
        ports:
          - "7000:7000"
 
    ui-foh:
        container_name: orchard_ui_foh
        build: ./orchard-ui-foh
        hostname: ui-foh
         
        links:
          - api

        volumes:
          - ./orchard-ui-foh:/orchard_ui_foh  
          - /orchard_ui_foh/node_modules
        ports:
          - "7004:7004"

    ui-boh:
        container_name: orchard_ui_boh
        build: ./orchard-ui-boh
        hostname: ui-boh
         
        links:
          - api

        volumes:
          - ./orchard-ui-boh:/orchard_ui_boh
          - /orchard_ui_boh/node_modules
        ports:
          - "7005:7005"

    api:
        container_name: orchard_api
        build: ./orchard-api
        hostname: api
        depends_on:
          - db
         
        volumes:
          - ./orchard-api:/orchard_api
          - /orchard_api/node_modules
        links: 
          - db 
          - pptx
        ports:
          - "7001:7001"
          - "9229:9229"